### ISSUE TITLE
COPY failed: forbidden path outside the build context

### ISSUE THREAD

**Issue by tunjan** [MarkKorvin/MLE_basic_example#9]
### Description
After generating the data and following the steps provided in the `README.md` file I get an error stating that the data path is outside of the build context

### Steps to Reproduce

1. Add folder to workspace in VSCode
2. Execute `data_generation.py` file
3. Run the dockerfile from the training folder

### Expected Behavior
The dockerfile compiles without errors

### Actual Behavior
```
Sending build context to Docker daemon  138.8kB
Step 1/11 : FROM python:3.10
 ---> ddc4de90bbec
Step 2/11 : ARG settings_name=settings.json
 ---> Using cache
 ---> b9ca60ac0e7f
Step 3/11 : ENV CONF_PATH=${settings_name}
 ---> Using cache
 ---> 081be63d9d4e
Step 4/11 : WORKDIR /app
 ---> Using cache
 ---> ce6626966427
Step 5/11 : COPY ../data/ /app/data
COPY failed: forbidden path outside the build context: ../data/ ()
```

### Screenshots
![image](https://github.com/MarkKorvin/MLE_basic_example/assets/76629093/a9084ec7-f10a-4a27-82b9-b640b6706c15)

### Environment
- Operating System: Linux
- Python environment: Conda
-  IDE: VSCodium (VSCode without Microsoft telemetry)
-  Docker: 24.0.7

### Possible Solution
Editing the dockerfile and subtituting `../data/ /app/data` for `data/ /app/data` provided a temporal fix. (Same thing with other paths that include double dots)

**Comment by MarkKorvin** [comment]
Hi @tunjan, looks like your fix doesn't break anything for windows machines, so I've merged it into main branch [here](https://github.com/MarkKorvin/MLE_basic_example/pull/15/commits/c058ef5e0301e2225b69a3cdfbc75e15464dea3c)

**Comment by tunjan** [comment]
Thanks!
